/**
 * pi extension generated by pi-acp: bridges ACP `session/new` mcpServers into pi.
 *
 * pi-acp spawns `pi --mode rpc -e <this file>` with PI_ACP_MCP_SERVERS set to a
 * JSON array of MCP server specs. On load we connect each server and register
 * its tools as native pi tools (`mcp_<server>_<tool>`).
 *
 * This file is bundled (tsup entry `pi-mcp-extension`) with the MCP SDK inlined,
 * so it has no runtime dependency on pi-acp's node_modules.
 */

import { Client } from '@modelcontextprotocol/sdk/client/index.js'
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js'
import { StreamableHTTPClientTransport } from '@modelcontextprotocol/sdk/client/streamableHttp.js'
import { SSEClientTransport } from '@modelcontextprotocol/sdk/client/sse.js'

const ENV_KEY = 'PI_ACP_MCP_SERVERS'
const CONNECT_TIMEOUT_MS = 15_000
const TOOL_NAME_MAX = 64

type McpEnvVar = { name: string; value: string }

type AcpMcpServerSpec = {
  name: string
  /** Absent/'stdio' => spawn command; 'http'/'sse' => connect to url. */
  type?: string
  command?: string
  args?: string[]
  env?: McpEnvVar[]
  url?: string
  headers?: McpEnvVar[]
}

type PiContentBlock = { type: 'text'; text: string } | { type: 'image'; data: string; mimeType: string }

type PiToolResult = {
  content: PiContentBlock[]
  details?: unknown
}

// Minimal slice of pi's ExtensionAPI used here; pi passes a much richer object.
type PiExtensionApi = {
  on(event: 'session_start' | 'session_shutdown', handler: (event: unknown, ctx: unknown) => unknown): void
  registerTool(tool: {
    name: string
    label: string
    description: string
    parameters: Record<string, unknown>
    execute: (
      toolCallId: string,
      params: Record<string, unknown>,
      signal?: AbortSignal,
      onUpdate?: (partial: PiToolResult) => void
    ) => Promise<PiToolResult>
  }): void
}

function log(message: string): void {
  // pi rpc mode surfaces stderr to the ACP client logs; keep stdout clean.
  console.error(`[pi-acp-mcp] ${message}`)
}

function sanitizePart(value: string): string {
  const cleaned = value
    .toLowerCase()
    .replace(/[^a-z0-9_]/g, '_')
    .replace(/_+/g, '_')
  return cleaned.replace(/^_+|_+$/g, '') || 'x'
}

function mcpToolName(serverName: string, toolName: string): string {
  const raw = `mcp_${sanitizePart(serverName)}_${sanitizePart(toolName)}`
  if (raw.length <= TOOL_NAME_MAX) return raw
  let hash = 0
  for (let i = 0; i < raw.length; i += 1) hash = (hash * 31 + raw.charCodeAt(i)) >>> 0
  return `${raw.slice(0, TOOL_NAME_MAX - 9)}_${hash.toString(16).padStart(8, '0')}`
}

function sanitizeParameters(schema: unknown): Record<string, unknown> {
  if (schema && typeof schema === 'object' && !Array.isArray(schema)) {
    const candidate = { ...(schema as Record<string, unknown>) }
    delete candidate.$schema
    if (candidate.type === 'object' || candidate.properties || candidate.anyOf || candidate.allOf || candidate.oneOf) {
      if (!candidate.type) candidate.type = 'object'
      return candidate
    }
  }
  return { type: 'object', properties: {}, additionalProperties: true }
}

function toText(value: unknown): string {
  if (typeof value === 'string') return value
  try {
    return JSON.stringify(value, null, 2)
  } catch {
    return String(value)
  }
}

function mapContent(content: unknown): PiContentBlock[] {
  if (!Array.isArray(content)) return [{ type: 'text', text: toText(content) }]
  const out: PiContentBlock[] = []
  for (const block of content) {
    if (!block || typeof block !== 'object') continue
    const b = block as Record<string, any>
    switch (b.type) {
      case 'text':
        out.push({ type: 'text', text: String(b.text ?? '') })
        break
      case 'image':
        out.push({ type: 'image', data: String(b.data ?? ''), mimeType: String(b.mimeType ?? 'image/png') })
        break
      case 'resource': {
        const res = (b.resource ?? {}) as Record<string, any>
        if (typeof res.text === 'string') out.push({ type: 'text', text: res.text })
        else if (typeof res.blob === 'string')
          out.push({ type: 'text', text: `[resource ${String(res.uri ?? '')}] ${res.blob}` })
        else out.push({ type: 'text', text: toText(b) })
        break
      }
      case 'resource_link':
        out.push({ type: 'text', text: `[resource_link] ${String(b.uri ?? b.name ?? '')}` })
        break
      default:
        out.push({ type: 'text', text: toText(b) })
    }
  }
  return out.length ? out : [{ type: 'text', text: '(empty result)' }]
}

function envListToRecord(list: McpEnvVar[] | undefined): Record<string, string> {
  const out: Record<string, string> = {}
  for (const e of list ?? []) {
    if (e && typeof e.name === 'string') out[e.name] = String(e.value ?? '')
  }
  return out
}

function headersToRecord(list: McpEnvVar[] | undefined): Record<string, string> {
  return envListToRecord(list)
}

type ConnectedServer = { spec: AcpMcpServerSpec; client: Client }

async function connectServer(spec: AcpMcpServerSpec): Promise<ConnectedServer> {
  const client = new Client({ name: `pi-acp-${spec.name}`, version: '0.0.0' }, { capabilities: {} })

  let transport: StdioClientTransport | StreamableHTTPClientTransport | SSEClientTransport
  const kind = spec.type ?? 'stdio'
  if (kind === 'http') {
    if (!spec.url) throw new Error(`MCP server "${spec.name}" is http but has no url`)
    transport = new StreamableHTTPClientTransport(new URL(spec.url), {
      requestInit: { headers: headersToRecord(spec.headers) }
    })
  } else if (kind === 'sse') {
    if (!spec.url) throw new Error(`MCP server "${spec.name}" is sse but has no url`)
    transport = new SSEClientTransport(new URL(spec.url), {
      requestInit: { headers: headersToRecord(spec.headers) }
    })
  } else {
    if (!spec.command) throw new Error(`MCP server "${spec.name}" is stdio but has no command`)
    transport = new StdioClientTransport({
      command: spec.command,
      args: spec.args ?? [],
      env: envListToRecord(spec.env),
      stderr: 'inherit'
    })
  }

  const ac = new AbortController()
  const timer = setTimeout(() => ac.abort(), CONNECT_TIMEOUT_MS)
  try {
    await Promise.race([
      client.connect(transport),
      new Promise<never>((_resolve, reject) => {
        ac.signal.addEventListener('abort', () => reject(new Error('connect timed out')))
      })
    ])
  } finally {
    clearTimeout(timer)
  }

  return { spec, client }
}

function readServersFromEnv(): AcpMcpServerSpec[] {
  const raw = process.env[ENV_KEY]
  if (!raw) return []
  try {
    const parsed = JSON.parse(raw) as unknown
    if (!Array.isArray(parsed)) return []
    return parsed.filter(
      (s): s is AcpMcpServerSpec => !!s && typeof s === 'object' && typeof (s as AcpMcpServerSpec).name === 'string'
    )
  } catch (e) {
    log(`invalid ${ENV_KEY}: ${(e as Error)?.message ?? e}`)
    return []
  }
}

export default async function piAcpMcpExtension(pi: PiExtensionApi): Promise<void> {
  const servers = readServersFromEnv()
  if (!servers.length) return

  const connected: ConnectedServer[] = []

  for (const spec of servers) {
    if (spec.type === 'acp') {
      log(`skipping "${spec.name}": ACP-transport MCP servers are not supported`)
      continue
    }
    try {
      const conn = await connectServer(spec)
      connected.push(conn)
    } catch (e) {
      log(`failed to connect MCP server "${spec.name}": ${(e as Error)?.message ?? e}`)
    }
  }

  for (const { spec, client } of connected) {
    let tools: Array<{ name: string; description?: string; inputSchema?: unknown }> = []
    try {
      let cursor: string | undefined
      do {
        const listed = await client.listTools(cursor ? { cursor } : undefined)
        tools = tools.concat((listed?.tools ?? []) as typeof tools)
        cursor = typeof listed?.nextCursor === 'string' && listed.nextCursor ? listed.nextCursor : undefined
      } while (cursor)
    } catch (e) {
      log(`tools/list failed for "${spec.name}": ${(e as Error)?.message ?? e}`)
      continue
    }

    for (const tool of tools) {
      const piToolName = mcpToolName(spec.name, tool.name)
      pi.registerTool({
        name: piToolName,
        label: `${spec.name}: ${tool.name}`,
        description: tool.description ?? `MCP tool "${tool.name}" from server "${spec.name}"`,
        parameters: sanitizeParameters(tool.inputSchema),
        async execute(_toolCallId, params, signal) {
          const result = (await client.callTool(
            { name: tool.name, arguments: params },
            undefined,
            signal ? { signal } : undefined
          )) as { content?: unknown; isError?: boolean }
          const content = mapContent(result?.content)
          if (result?.isError) {
            const text = content.map(c => (c.type === 'text' ? c.text : `[${c.type}]`)).join('\n')
            throw new Error(text || `MCP tool "${tool.name}" failed`)
          }
          return { content, details: result }
        }
      })
    }
    log(`registered ${tools.length} tool(s) from "${spec.name}"`)
  }

  pi.on('session_shutdown', () => {
    for (const { client } of connected.splice(0)) {
      void client.close().catch(() => {})
    }
  })
}
